spring.application.name=WorldClassesBooking

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/WorldClasses
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#ORM s/w specific properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

